run both actions and verify user IDs match

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,5 +1,6 @@
-name: 'Pluralsight Demo: Custom Slack Action'
-description: 'Pings an organizational contact in Slack using a custom integration'
+name: 'Pluralsight Demo: Send Status Notification to Slack (Composite)'
+description: 'Sends the status of the GitHub Action to the user via Slack'
+
 inputs:
   github-token:
     description: 'The GitHub token to authenticate with GitHub API'
@@ -13,25 +14,37 @@ inputs:
   slack-bot-token:
     description: 'The Slack bot token to post messages'
     required: true
-outputs:
-  time:
-    description: 'The time we sent the message'
+
 runs:
   using: 'composite'
   steps:
 
   - uses: './get-employee-js-action'
-    id: get-employee
+    id: get-employee-js
     with:
       github-username: ${{ inputs.github-username }}
       github-token: ${{ inputs.github-token }}
       slack-token: ${{ inputs.slack-token }}
 
+  - uses: './get-employee-docker-action'
+    id: get-employee-docker
+    with:
+      github-username: ${{ inputs.github-username }}
+      github-token: ${{ inputs.github-token }}
+      slack-token: ${{ inputs.slack-token }}
+
+  - name: Verify Slack user IDs match
+    run: |
+      echo "::error::Slack user IDs do not match from JS and Docker"
+      exit 1
+    if: steps.get-employee-js.outputs.slack-user-id != steps.get-employee-docker.outputs.slack-user-id
+
   - name: Post to a Slack user
     id: slack
     uses: slackapi/slack-github-action@v1.26.0
+    if: steps.get-employee-js.outputs.slack-user-id == steps.get-employee-docker.outputs.slack-user-id
     with:
-      channel-id: '${{ steps.get-employee.outputs.slack-user-id }}'
+      channel-id: '${{ steps.get-employee-js.outputs.slack-user-id }}'
       slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
     env:
       SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}
